### PR TITLE
Use libalpm directly instead of calling vercmp

### PR DESCRIPTION
**Pull request by Tyilo**

### CODE REVIEW

**Comment by actionless** [comment]
```diff
diff --git a/pikaur/package_update.py b/pikaur/package_update.py
index d2ac4f2..2e195e7 100644
--- a/pikaur/package_update.py
+++ b/pikaur/package_update.py
@@ -1,8 +1,7 @@
 from .core import (
-    DataType,
-    SingleTaskExecutor, MultipleTasksExecutorPool
+    DataType, SingleTaskExecutor,
 )
-from .version import compare_versions_async
+from .version import compare_versions
 from .pacman import PacmanTaskWorker, PackageDB
 from .aur import find_aur_packages
 
@@ -42,41 +41,21 @@ def find_repo_updates():
     return repo_packages_updates
 
 
-class FindAurUpdatesTask():
-
-    def __init__(self, package_versions, result):
-        self.package_versions = package_versions
-        self.result = result
-
-    async def get_task(self, _loop):
-        result = self.result
-        package_versions = self.package_versions
-
+def find_aur_updates(package_versions):
+    aur_pkgs_info, not_found_aur_pkgs = find_aur_packages(
+        package_versions.keys()
+    )
+    aur_updates = []
+    for result in aur_pkgs_info:
         pkg_name = result.Name
         aur_version = result.Version
         current_version = package_versions[pkg_name]
-        compare_result = await compare_versions_async(current_version, aur_version)
+        compare_result = compare_versions(current_version, aur_version)
         if compare_result < 0:
-            aur_update = PackageUpdate(
+            aur_updates.append(PackageUpdate(
                 Name=pkg_name,
                 New_Version=aur_version,
                 Current_Version=current_version,
                 Description=result.Description
-            )
-            return aur_update
-
-
-def find_aur_updates(package_versions):
-    aur_pkgs_info, not_found_aur_pkgs = find_aur_packages(
-        package_versions.keys()
-    )
-    aur_updates = [
-        update for update in MultipleTasksExecutorPool({
-            result.Name: FindAurUpdatesTask(
-                package_versions=package_versions,
-                result=result
-            ) for result in aur_pkgs_info
-        }).execute().values()
-        if update
-    ]
+            ))
     return aur_updates, not_found_aur_pkgs
diff --git a/pikaur/version.py b/pikaur/version.py
index 560a107..45ce2c3 100644
--- a/pikaur/version.py
+++ b/pikaur/version.py
@@ -40,7 +40,7 @@ def compare_versions_bak(current_version, new_version):
 _CACHED_VERSION_COMPARISONS = {}
 
 
-async def compare_versions_async(current_version, new_version):
+def compare_versions(current_version, new_version):
     """
     vercmp is used to determine the relationship between two given version numbers.
     It outputs values as follows:
@@ -57,10 +57,6 @@ async def compare_versions_async(current_version, new_version):
     return _CACHED_VERSION_COMPARISONS[current_version][new_version]
 
 
-def compare_versions(current_version, new_version):
-    return execute_task(compare_versions_async(current_version, new_version))
-
-
 def compare_versions_test():
     import traceback
 
```

**Comment by actionless** [comment]
together with the patch above it will be :+1: to merge

**Comment by actionless** [comment]
Thanks!

**Comment by Tyilo** [comment]
@actionless I don't think `_CACHED_VERSION_COMPARISONS` are needed anymore as it should be pretty fast:

```
> %timeit libalpm.alpm_pkg_vercmp(b'1:1.2.3-abcdef', b'1:1.2.3-abcdef')
269 ns ± 4.38 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by actionless** [comment]
good point

**Pull request merged**
