### PR TITLE
Added portuguese translations

### PR DESCRIPTION
**Pull request by alexandreslopes**
Hi,
I did not translate Y / N, because of a different writing system.

README.md translated into Portuguese for a better understanding of Brazilians.

PS: Probably this translation can be improved.

Very good project, I'm rooting for him and for you.

### CODE REVIEW

**Comment by Yardanico** [comment]
You don't need to translate readme

**Comment by actionless** [comment]
you can just rename it from README.md to README_pt.md

**Comment by AladW** [comment]
Now you removed the original english README.md....

**Comment by alexandreslopes** [comment]
Well, I'm trying to help you the best, but I'm new to it, using Github. Please excuse any mistake or inconvenience.

To come from pacaur, and I really want this project to take off!

Thank you in advance for the help and patience of all.

**Comment by actionless** [comment]
thanks!

in the last commit i see you did removed `README_pt_BR.md`.
was it intentional?

**Comment by alexandreslopes** [comment]
Hi,

Yes, it was intentional. I came to the conclusion that it is unnecessary, if someone wants to see the translation uses google Translator .... kkkkk

And so the project gets leaner.

**Comment by actionless** [comment]
thanks a lot for the great work on translating this!

**Pull request merged**
