### PR TITLE
enhance colour section

### PR DESCRIPTION
**Pull request by mattia-b89**
add information about colours: palette and its "origin"

### CODE REVIEW

**Comment by mattia-b89** [comment]
part of issue #418

**Comment by actionless** [comment]
please check https://github.com/actionless/pikaur#documentation

**Comment by mattia-b89** [comment]
I am not a GIT/GITHUB expert.
What I have to do?

**Comment by actionless** [comment]
https://help.github.com/en/github/managing-files-in-a-repository/adding-a-file-to-a-repository-using-the-command-line

**Comment by actionless** [comment]
i think eventually i should move `make man` step to be done automatically by travis when merging, but so far it works like that :(

**Comment by mattia-b89** [comment]
I used github online interface, where is the problem?

**Comment by actionless** [comment]
you'll need to clone the repo locally in order to generate the manpages from readme.md file

**Pull request closed without merging**
