### PR TITLE
Russian translation (minor fix #2)

### LINKED ISSUE #2: no fakeroot check
Hi, 
On a fresh arch install, the install command has failed because of fakeroot package missing.
I installed it and it's ok, pikaur works, but it would be nice if it's added in the build script ?
Thanks for your works !
William

### PR DESCRIPTION
**Pull request by Drommer**

### CODE REVIEW

**Comment by Drommer** [comment]
> Базовый пакет?

In AUR russian interface same translate.

**Comment by actionless** [comment]
link?

**Comment by Drommer** [comment]
> link?

For example: https://aur.archlinux.org/packages/mpv-full/

**Comment by actionless** [comment]
I see.

In that case other translations for `-Si` also could be improved in the same way

**Pull request merged**
