### PR TITLE
Replace the "input" with "get_answer" function

### PR DESCRIPTION
**Pull request by plague-doctor**
get_answer function reads a single character from STDIN and returns it back as a lowered character. One can pass the acceptable answers as an 'answers' string parameter. The capitalised letter in the `answers` string is the default value, which will be returned when invalid answer is given (including Enter).
The function adheres to the pikaur's minimal dependencies principle. It requires only a 'tty' standard python library.

### CODE REVIEW

**Comment by plague-doctor** [comment]
A fix for ctrl+d and ctrl+c in the last commit. Good catch :+1: Also the wrong answer will return an empty string instead of default value.
A minimal dependencies in my understanding was using no special python libraries (non-pip install ones).

This function is to minimise the amount of pressed keys, which I have found more beneficial in long run, than an occasional clearing the terminal. But it is up to a debate, I guess...

**Comment by actionless** [comment]
which extra non-pip packages are you talking about?

and i still not getting what is the reason to replace `input()`

**Comment by plague-doctor** [comment]
I just thought, that by 'minimal dependencies' you meant 'do not use packages which need to be installed on top of the basic python installation'. 

Well, it may be just me, but I do not like to press ENTER after a single character option. In my opinion, if one requires a single character answer, why to wait for ENTER to be pressed?
If the convenience is not enough reason to replace `input()`, please close the PR.

**Comment by actionless** [comment]
i think it's fine here to follow pacman in waiting for Enter to be pressed.
i know it's extra key press but it's better to be more explicit when asking for confirmations -- that could be quite discorouging when accidential press of single key confirming/anceling some operation accidentially

**Comment by actionless** [comment]
thanks for your effort working on the changes however i am not convinced into merging this

**Pull request closed without merging**
