### PR TITLE
chore(locale): update es.po and fr.po

### PR DESCRIPTION
**Pull request by Bundy01**
Hi,

I have a doubt about the translation `[Y]es ({reason})`: I have translated the `[Y]es`.

And on the translation of `don't pull already cloned PKGBUILD`, I translated `pull` as `extract`.

Tell me if it fits, if not I'd like synonyms.
Regards.

### CODE REVIEW

**Comment by actionless** [comment]
pull meant in context like `git pull`

**Comment by actionless** [comment]
regarding [y]es/[s]i - please just check how it's implemented in `pacman` to keep the same style of translation

**Comment by Bundy01** [comment]
For the translation of PULL, I don't really know how to translate it. Hence my doubt, what do you think about FUSION?

For the [Y]es, I looked in the source code of Pacman and I found nothing in the .po files :/

**Comment by actionless** [comment]
idk regarding the pull since idk that language :)

regarding po file: https://gitlab.archlinux.org/pacman/pacman/-/blob/master/src/pacman/po/es.po

**Comment by actionless** [comment]
#: src/pacman/util.c:1607
#, c-format
msgid "[Y/n]"
msgstr "[S/n]"

#: src/pacman/util.c:1609
#, c-format
msgid "[y/N]"
msgstr "[s/N]"

**Comment by Bundy01** [comment]
For Pacman, there is no `[Y]es ({reason})` but the example you gave me is well translated. So for me, it's ok.

I also think that the translation of pull is correct:

**Comment by actionless** [comment]
thanks a lot!

**Pull request merged**
