### PR TITLE
Correctly source paths

### LINKED ISSUE #801: XDG variables / config-settings confusion
```
pikaur -Sy

```

##### Prerequisites:
environment set to:  
XDG_CACHE_HOME=$HOME/.local/tmp  
XDG_DATA_HOME=$HOME/.local/data

##### Description:
every time you run pikaur, 
```
cachepath = $HOME/.cache
datapath = $HOME/.local/share
```
gets addded to pikaur.conf independ of your XDG variables and it then uses cachepath for cache.  
Curiously, it then still uses `~/.local/data/pikaur` for aur_repos.

So, in summary:
- XDG_CACHE_HOME gets ignored for config
- - cachepath in config gets used
- XDG_DATA_HOME gets ignored for config
- - but used for repo backups

### PR DESCRIPTION
**Pull request by samuel-jimenez**
Prefer environment variables over config; sync config based on first-run environment (Fixes #801).

### CODE REVIEW

**Comment by actionless** [comment]
@Baerbeisser could you test pls?

**Comment by Baerbeisser** [comment]
Ah, sorry, yes.

Mh, i get
```
  File "/home/dani/pikaur/pikaur/main.py", line 431, in main
    create_dirs()
  File "/home/dani/pikaur/pikaur/main.py", line 381, in create_dirs
    mkdir(AurReposCachePath()())
  File "/home/dani/pikaur/pikaur/core.py", line 389, in mkdir
    path.mkdir(parents=True)
  File "/usr/lib/python3.12/pathlib.py", line 1315, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.12/pathlib.py", line 1315, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.12/pathlib.py", line 1315, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)

PermissionError: [Errno 13] Permission denied: '/home/dani.'
```
still pikaur.conf with wrong cachepath + datapath generated.

[pikaur.conf.tar.gz](https://github.com/user-attachments/files/15593251/pikaur.conf.tar.gz)

(tf, Github doesn't support conf/cfg files??)

**Comment by samuel-jimenez** [comment]
are you using `$HOME/.local` or `$HOME./local`?

**Comment by Baerbeisser** [comment]
Oops. 😳

But now i get
```
$ LC_ALL=C python3 pikaur.py -Sy
sudo: pikaur.py: command not found
```
still same with pikaur.conf

**Comment by samuel-jimenez** [comment]
Does this still happen if you delete the entries from your config? They should only be created if they don't exist yet, but they will be overridden if you have the variables set.

**Comment by Baerbeisser** [comment]
No, they only get recreated exactly the same.  `~/.cache` and `~/.local/share`

I know that those are intended by XDG to be used if no variable is set, so i guess that check fails?

**Comment by samuel-jimenez** [comment]
Is pikaur using the variables at all?
Does using `--pikaur-config` change anything?
This branch has increased output:
https://github.com/samuel-jimenez/pikaur/tree/debug-xdg
Can you post those logs?

**Comment by Baerbeisser** [comment]
[pikaur.log](https://github.com/user-attachments/files/15641800/pikaur.log)

Looks like it does get the variables but then
```
_CachePathDefault
--xdg-cache-home:  /home/dani/.local/tmp
XDG_CACHE_HOME:  None

_DataPathDefault
--xdg-data-home:  /home/dani/.local/data
XDG_DATA_HOME:  None

_UserCacheRoot
--xdg-cache-home:  /home/dani/.local/tmp
XDG_CACHE_HOME:  None
config:  /home/dani/.cache

DataRoot
--xdg-data-home:  /home/dani/.local/data
XDG_DATA_HOME:  None
config:  /home/dani/.local/share
```

**Comment by samuel-jimenez** [comment]
Thanks, and if you use `--pikaur-config=/home/dani/.config/pikaur0.conf`?

**Comment by samuel-jimenez** [comment]
The branches only differ by the amount of output they produce.

This is now working as intended by finding the default paths if and only if they do not exist.
If you want them to be regenerated, you can comment them out in your original config.
e.g., `# cachepath = ..`

**Comment by Baerbeisser** [comment]
My bad, i didn't update the changes of this branch. Though now i only get

`:: error: Read damn arch-wiki before borking your computer`

**Comment by Baerbeisser** [comment]
> I don't know that message, but I don't think it's from pikaur.

It's literally
```
$ ./pikaur.py -Sy
:: error: Read damn arch-wiki before borking your computer
```

> pikaur.conf exists, with cachepath and datapath removed.

Sorry for the misunderstanding, what i meant is, the error isn't because of a missing pikaur.conf. And i removed those two lines, so pikaur should update them again. They do get re-created while pikaur throws the error.

**Comment by samuel-jimenez** [comment]
> > I don't know that message, but I don't think it's from pikaur.
> 
> It's literally
> 
> ```
> $ LC_ALL=C ./pikaur.py -Sy
> :: error: Read damn arch-wiki before borking your computer
> ```
> 
That triggers it for you, but the error is not in pikaur.
If you `grep -r borking .` in the pikaur directory, you will get no results. If I had to guess, I would look at GNOME.

> > pikaur.conf exists, with cachepath and datapath removed.
> 
> Sorry for the misunderstanding, what i meant is, the error isn't because of a missing pikaur.conf. And i removed those two lines, so pikaur should update them again. They do get re-created while pikaur throws the error. But again
> 
> ```
> cachepath = /home/dani/.cache
> datapath = /home/dani/.local/share
> ```
> 
> I just use the "Download as zip" function, delete the content of the folder and extract there.
If you follow that same procedure with the [debug-xdg](https://github.com/samuel-jimenez/pikaur/tree/debug-xdg) branch, what is the result?

**Comment by Baerbeisser** [comment]
I use XFCE and i *do* have custom login scripts but `grep -Irn borking` shows nothing in /etc and ~/.config. And it's in the same shell as before the update.

But i do find
```
pikaur/main.py:450:                "Read damn arch-wiki before borking your computer",
```
You searched bork*ed* instead of bork*ing*. 😉

debug-xdg replaces cachepath and datapath correctlyy with XDG_* vars content.

**Comment by samuel-jimenez** [comment]
:facepalm: Well, that explains it! It came in on 0b94fd0, and I haven't pulled that one yet.

It won't be on main until this gets merged. You can test with this branch:
https://github.com/samuel-jimenez/pikaur/tree/prefer-env-vars

**Comment by Baerbeisser** [comment]
Yep, this branch works as it should. datapath and cachepath are correct.

About the error, this part in main.py seems new, will that check for base-devel remain?  
If so, it will somewhat break support for doas, since sudo is part of base-devel. And if you use doas you likely will remove sudo and removing sudo removes base-devel. To which a work-around is to install the individual tools separately but then no base-devel group will be detected.

**Comment by samuel-jimenez** [comment]
I am not certain, as I did not author those changes. If you will kindly open a new issue we can get that resolved.

**Comment by actionless** [comment]
any update on this one?

i'm planning to make 1.22 release soon, and i need this feature either fixed or unmerged

**Comment by samuel-jimenez** [comment]
It has been fixed and is ready to merge

**Comment by actionless** [comment]
thanks a lot!

**Comment by Baerbeisser** [comment]
Though the check for base-devel with warning about borking your computer still remains if you used the workarounds to install doas.

**Comment by actionless** [comment]
but it's not related to this issue, right?

**Comment by Baerbeisser** [comment]
My bad, sorry.

**Comment by actionless** [comment]
@Baerbeisser no worries, feel free to elaborate further on that in that ticket which you created 👍

**Pull request merged**
