### PR TITLE
Update locale

### PR DESCRIPTION
**Pull request by Bundy01**
Update ES and FR.

Should I delete the comments at the end of the file for the next PR?
Thanks.

### CODE REVIEW

**Comment by actionless** [comment]
thanks a lot!

if you asking about fuzzy -- i would leave it as is but since you contributing to translations more than me i'll leave decision on you -- just do it in separate commit, so the change could be reverted

**Comment by Bundy01** [comment]
My question was for the code that is commented at the end of the files. Is it useful to keep it?

**Comment by Bundy01** [comment]
I take the example of the fr.po file: lines 652 to 696.

**Comment by actionless** [comment]
ah, i see, those are translations for already removed strings

so it's still up to you :-)

**Comment by Bundy01** [comment]
If it doesn't make sense, I'll delete the next PR.
Thank you.

**Comment by actionless** [comment]
those comment lines could be useful for translators if the same already removed strings will be returned back to the app

since pikaur more or less stabilized by now i don't think too much strings will be changed again soon so it's quite safe to remove them

**Pull request merged**
