### PR TITLE
Create it.po

### PR DESCRIPTION
**Pull request by mattia-b89**
initial Italian translation

### CODE REVIEW

**Comment by mattia-b89** [comment]
**a)** refers to https://github.com/actionless/pikaur/issues/395

---

**b)** this is my first PR, so if I have done something wrong, please tell me!

---

**c)** this is also my first official `.po` work and I have some technical question:  
the first refers to strings containing keys to be pressed when answering questions, like `[e] edit PKGBUILD`.  
In this case "**e**" stands for _**e**dit_, in English it fits;  
in Italian (or any other different language) should we keep "e" or change it with the most fitting native key?  
e.g. _**e**dit_ in Italian is _**m**odifica_, thus [**e**] should change to [**m**] ?

**Comment by actionless** [comment]
c) during working on translations another contributor already raised such a question: https://github.com/actionless/pikaur/issues/382

i don't have a clear answer for that, i guess just see how it's done in Pacman itself for your locale, if it translates `[Y/n]` to `[S/n]` or not

**Comment by mattia-b89** [comment]
How can I easily test languages other than locale?

**Comment by actionless** [comment]
@mattia-b89 

```
$ env LC_ALL=fr_FR.utf8 LANG=fr LANGUAGE=fr pikaur -Si oomox
URL AUR Git     : https://aur.archlinux.org/oomox.git
Nom             : oomox
Base du Paquet  : oomox
```

**Comment by mattia-b89** [comment]
I have two questions:
**1)** I completed translating it.po; _how can I upload it?_  
**2)** .po files changed upstream; _how do I merge old translation and new one?_

**Comment by actionless** [comment]
1) https://help.github.com/en/articles/adding-a-file-to-a-repository

2) you don't need to upload any files except for it.po as part of this PR

**Comment by actionless** [comment]
thanks a lot!

**Comment by mattia-b89** [comment]
I think you can "announce" new Italian translation on AUR page in order to get feedbacks!

**Comment by actionless** [comment]
such kind of announcements are made in the Pikaur AUR repo CHANGELOG.txt file:

https://aur.archlinux.org/cgit/aur.git/commit/?h=pikaur&id=db665eb9d381a3d01e84b745959cb6672b39a6a7

so when observing aur pkg diff users can see the new lines on the changelog

**Comment by mattia-b89** [comment]
Great!

**Pull request merged**
