### PR TITLE
Small optimizations

### PR DESCRIPTION
**Pull request by dnsjts**
This change is [Reviewable](https://reviewable.io/reviews/actionless/pikaur/219)

### CODE REVIEW

**Comment by actionless** [comment]
what is the point of this optimization?

**Comment by actionless** [comment]
just to clarify: git there is fetching repo from aur (with PKGBUILD), not the repo with sources of the app which gonna be built

**Comment by dnsjts** [comment]
Oh, in this case feel free to close this PR, I originally wanted to reduce the size of the repo with the sources.

**Comment by Morganamilo** [comment]
If you did manage to do this for the sources, pkgbuilds often checkout commits or use tags. Adding depth=1 to the sources would beak a lot of pkgbuilds.

**Pull request closed without merging**
