### PR TITLE
Sort packages to update by name

### PR DESCRIPTION
**Pull request by Tyilo**

### CODE REVIEW

**Comment by actionless** [comment]
they already sorted by 'majority' of the update (see `sort_by` var few lines above)

mb you could make a --sortby option which would apply also to other sortable views (like -Ss or -Qs)

**Comment by Tyilo** [comment]
Hmm, do ties get sorted name after majority?

**Comment by actionless** [comment]
no

**Comment by Tyilo** [comment]
Shouldn't they?

**Comment by actionless** [comment]
i don't mind, however i don't see too much sense in that since their primary sort is totally unrelated to naming

ex.,  when primary sort is repo, and secondary is package, or 1)repo-2)group-3)package -- that creates some sort of tree structure which that sorting will logically represent

**Comment by actionless** [comment]
so, feel free to open PR for secondary search and/or improving search by version diff

thank you for your effort and interest to the project!

**Pull request closed without merging**
